language: ruby

services:
  - redis-server

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile

script: bundle exec rake test

cache: bundler
